// This file will be auto-generated by typesafe-i18n
// Do not edit manually

import type { BaseTranslation } from 'typesafe-i18n'

export interface Translation extends BaseTranslation {
  common: {
    loading: string
    error: string
    save: string
    cancel: string
    confirm: string
    back: string
    next: string
    close: string
    continue: string
    skip: string
  }
  navigation: {
    locations: string
    goals: string
    market: string
    factions: string
    skills: string
  }
  resources: {
    credits: string
    condition: string
    stress: string
    energy: string
    reputation: string
  }
  market: {
    buy: string
    sell: string
    price: string
    amount: string
    total: string
    inventory: string
    search: string
    insufficient_funds: string
  }
  goals: {
    available: string
    active: string
    completed: string
    failed: string
    requirements: string
    rewards: string
    accept: string
    invest: string
    no_goals: string
  }
  tutorial: {
    skip: string
    next: string
    previous: string
  }
  menu: {
    settings: string
    save_game: string
    load_game: string
    new_game: string
    quit: string
    return_menu: string
  }
}